// airtableConfig.js
const AIRTABLE_TOKEN = "TU_TOKEN_NUEVO_PRIVADO";
const BASE_ID = "appraIuHWdh5tA4FU";

const endpoints = {
  RESERVAS: "RESERVAS",
  CLIENTAS: "CLIENTAS",
  VESTIDOS: "VESTIDOS",
  CHECKLIST: "CHECKLIST",
  FINANZAS: "FINANZAS",
  "HORARIOS DISPONIBLES": "HORARIOS DISPONIBLES"
};
